### ISSUE TITLE
Bot crashes with `[HttpError]: other side closed`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/backportbot#421]
```
 /app/node_modules/@octokit/request/dist-node/index.js:156
     throw new import_request_error.RequestError(message, 500, {
           ^
 
 RequestError [HttpError]: other side closed
     at /app/node_modules/@octokit/request/dist-node/index.js:156:11
     at addReaction (/app/src/githubUtils.ts:37:2) {
   status: 500,
   request: {
     method: 'POST',
     url: 'https://api.github.com/repos/nextcloud/server/issues/comments/1953680517/reactions',
     headers: {
       accept: 'application/vnd.github.v3+json',
       'user-agent': 'octokit-rest.js/20.0.2 octokit-core.js/5.0.2 Node.js/20.11.1 (linux; x64)',
       authorization: 'token [REDACTED]',
       'content-type': 'application/json; charset=utf-8'
     },
     body: '{"content":"+1"}',
     request: { hook: [Function: bound bound register] }
   }
 }

```

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/backportbot/blob/c38e7033c503b16a3b9ed2fbebe402dc4821c489/src/backport.ts#L21-L27

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/backportbot/commit/4318e01232c696d3313b421467d6436e6f057fda seems to fix it

https://github.com/nextcloud/backportbot/blob/4318e01232c696d3313b421467d6436e6f057fda/src/backport.ts#L22-L27
